M48
; DRILL file {KiCad 8.0.4} date 2024-09-02T14:27:58-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-02T14:27:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X129.905Y-96.428
T2
X58.1Y-61.422
X104.3Y-61.422
X113.15Y-61.5
X125.75Y-61.5
T3
X125.93Y-107.04
M30
